### ISSUE TITLE
Deprecated brew.. stuff

### ISSUE THREAD

**Issue by SomeoneWeird** [buildkite/homebrew-buildkite#4]
```
➜ ~ git:(master) brew upgrade
Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:9:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:9:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:16:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:16:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!
```

👍

**Comment by toolmantim** [comment]
Jeez, but we have the `sha256` as well! Such warnings.

**Comment by keithpitt** [comment]
All fixed! 🚀
