### ISSUE TITLE
homebrew warnings

### ISSUE THREAD

**Issue by samritchie** [buildkite/homebrew-buildkite#5]
I’m getting a bunch for SHA1 related warnings when I upgrade. Assume you’re on it, but it told me to report it, so I’m doing it like a good little monkey.

```
==> Upgrading 1 outdated package, with result:
buildkite/buildkite/buildkite-agent 2.1.15
==> Upgrading buildkite/buildkite/buildkite-agent
Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:9:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:9:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:16:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/buildkite/homebrew-buildkite/buildkite-agent.rb:16:in `block in <class:BuildkiteAgent>'
Please report this to the buildkite/buildkite tap!```

**Comment by keithpitt** [comment]
Thanks for the heads up @samritchie! I think this should solve it: https://github.com/buildkite/agent/pull/364 then we'll remove the call to `sha1` in the `buildkite-agent.rb` file

**Comment by keithpitt** [comment]
All fixed! 🚀
